// Mock team data - replace with actual data
export const teamMembers = {
    "Board of Directors": [
      {
        id: 1,
        firstName: "Nicola",
        lastName: "Aram",
        jobTitle: "Marketing Manager",
        email: "info@ctskills.co.uk",
        phone: "012345678",
      },
      {
        id: 2,
        firstName: "John",
        lastName: "Smith",
        jobTitle: "CEO",
        email: "john@ctskills.co.uk",
        phone: "012345679",
      },
      {
        id: 3,
        firstName: "Sarah",
        lastName: "Johnson",
        jobTitle: "Director",
        email: "sarah@ctskills.co.uk",
        phone: "012345680",
      },
      {
        id: 4,
        firstName: "Michael",
        lastName: "Brown",
        jobTitle: "Finance Director",
        email: "michael@ctskills.co.uk",
        phone: "012345681",
      },
    ],
    "Senior Team": [
      {
        id: 5,
        firstName: "Emma",
        lastName: "Wilson",
        jobTitle: "Operations Manager",
        email: "emma@ctskills.co.uk",
        phone: "012345682",
      },
      {
        id: 6,
        firstName: "David",
        lastName: "Lee",
        jobTitle: "Head of Training",
        email: "david@ctskills.co.uk",
        phone: "012345683",
      },
      {
        id: 7,
        firstName: "Lisa",
        lastName: "Taylor",
        jobTitle: "Quality Manager",
        email: "lisa@ctskills.co.uk",
        phone: "012345684",
      },
      {
        id: 8,
        firstName: "Robert",
        lastName: "Green",
        jobTitle: "IT Manager",
        email: "robert@ctskills.co.uk",
        phone: "012345685",
      },
      {
        id: 9,
        firstName: "Jennifer",
        lastName: "White",
        jobTitle: "HR Manager",
        email: "jennifer@ctskills.co.uk",
        phone: "012345686",
        
      },
      {
        id: 10,
        firstName: "Thomas",
        lastName: "Black",
        jobTitle: "Compliance Manager",
        email: "thomas@ctskills.co.uk",
        phone: "012345687",
      },
    ],
    "Recruitment Team": [
      {
        id: 11,
        firstName: "Amanda",
        lastName: "Clark",
        jobTitle: "Recruitment Specialist",
        email: "amanda@ctskills.co.uk",
        phone: "012345688",
        
      },
      {
        id: 12,
        firstName: "James",
        lastName: "Miller",
        jobTitle: "Talent Acquisition",
        email: "james@ctskills.co.uk",
        phone: "012345689",
      },
      {
        id: 13,
        firstName: "Rachel",
        lastName: "Davis",
        jobTitle: "Recruitment Coordinator",
        email: "rachel@ctskills.co.uk",
        phone: "012345690",
        
      },
      {
        id: 14,
        firstName: "Mark",
        lastName: "Thompson",
        jobTitle: "Senior Recruiter",
        email: "mark@ctskills.co.uk",
        phone: "012345691",
      },
      {
        id: 15,
        firstName: "Sophie",
        lastName: "Anderson",
        jobTitle: "Recruitment Advisor",
        email: "sophie@ctskills.co.uk",
        phone: "012345692",
      },
      {
        id: 16,
        firstName: "Chris",
        lastName: "Roberts",
        jobTitle: "Talent Manager",
        email: "chris@ctskills.co.uk",
        phone: "012345693",
      },
    ],
    "Safeguarding & Prevention Team": [
      {
        id: 17,
        firstName: "Helen",
        lastName: "Walker",
        jobTitle: "Safeguarding Officer",
        email: "helen@ctskills.co.uk",
        phone: "012345694",
      },
      {
        id: 18,
        firstName: "Peter",
        lastName: "Evans",
        jobTitle: "Prevention Specialist",
        email: "peter@ctskills.co.uk",
        phone: "012345695",
      },
      {
        id: 19,
        firstName: "Michelle",
        lastName: "Hall",
        jobTitle: "Wellbeing Coordinator",
        email: "michelle@ctskills.co.uk",
        phone: "012345696",
      },
      {
        id: 20,
        firstName: "Kevin",
        lastName: "Young",
        jobTitle: "Support Manager",
        email: "kevin@ctskills.co.uk",
        phone: "012345697",
      },
      {
        id: 21,
        firstName: "Nicole",
        lastName: "King",
        jobTitle: "Safeguarding Lead",
        email: "nicole@ctskills.co.uk",
        phone: "012345698",
      },
      {
        id: 22,
        firstName: "Daniel",
        lastName: "Wright",
        jobTitle: "Prevention Manager",
        email: "daniel@ctskills.co.uk",
        phone: "012345699",
      },
    ],
  };